#THEORETICAL QUESTIONS:






## 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it  enhance Python's capabilities for numerical operations?


NumPy is a powerful library in Python that enhances its capabilities for scientific computing and data analysis by providing efficient tools for handling and performing operations on large, multi-dimensional arrays and matrices. Here's a brief explanation of its purpose and advantages:

#### Purpose of NumPy:

- Efficient Array Handling: NumPy introduces the ndarray object, which is optimized for high-performance storage and manipulation of large datasets.
- Numerical Operations: It provides a wide range of mathematical functions, such as linear algebra, statistical analysis, and element-wise operations on arrays, which are essential for scientific computing and data analysis.

####Advantages of NumPy:

- Performance: NumPy operations are vectorized, which means they are executed in C at a lower level, making them much faster than standard Python loops.
- Memory Efficiency: NumPy arrays are stored in contiguous memory locations, reducing memory overhead compared to Python lists, which makes handling large datasets more efficient.
- Multidimensional Arrays: NumPy supports N-dimensional arrays (e.g., matrices, tensors), which are crucial for complex computations in fields like machine learning, image processing, and physics simulations.
- Broad Functionality: It provides functions for linear algebra, random number generation, Fourier transforms, and statistical analysis, all of which are commonly used in scientific applications.

#### The NumPy Enhances Python’s Numerical Capabilities:

Vectorization allows for fast, element-wise operations without the need for loops.
Broadcasting makes it easy to perform operations on arrays of different shapes.
It integrates well with other scientific libraries like SciPy, Pandas, and scikit-learn, enabling a comprehensive Python ecosystem for data analysis and scientific work.




##2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

np.mean() :. Purpose: Calculates the arithmetic mean of an array (i.e., the sum of the elements divided by the number of elements)
- When to Use:When you want to compute the simple arithmetic mean (unweighted average) of the array.

np.average():. Purpose: Calculates the weighted average of an array. If no weights are specified, it behaves similarly to np.mean().
- When to Use: When we want to calculate a weighted average, where different values contribute more or less to the result based on their corresponding weights.
When we need additional information like the sum of weights (via the returned argument)






In [ ]:
#Choose np.mean() for simple averages.

#Choose np.average() for weighted averages.

import numpy as np

# Simple array
data = np.array([1, 2, 3, 4, 5])

# Using np.mean
mean = np.mean(data)
print("Mean:", mean)

# Using np.average (without weights)
avg = np.average(data)
print("Average:", avg)

# Using np.average (with weights)
weights = np.array([0.1, 0.2, 0.3, 0.2, 0.2])
weighted_avg = np.average(data, weights=weights)
print("Weighted Average:", weighted_avg)


Mean: 3.0
Average: 3.0
Weighted Average: 3.2


##3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

- Reversing a 1D Array:
Method 1: Using Slicing ([::-1]): For a 1D array, reversing is quite simple. We can use slicing reverse the array.

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the 1D array using slicing
reversed_1d = arr_1d[::-1]

print("Reversed 1D array:", reversed_1d)


Reversed 1D array: [5 4 3 2 1]


Reversing a 2D Array : With 2D arrays, we can reverse them along rows (axis 0), along columns (axis 1), or both axes at the same time.

- Reversing Along Rows (axis 0): Reversing along rows means flipping the array vertically.

- Method 1: Using Slicing ([::-1, :]) :We can slice the array along the rows (axis 0) using the following:

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse along rows (axis 0)
reversed_rows = arr_2d[::-1, :]

print("Reversed along rows (axis 0):\n", reversed_rows)



Reversed along rows (axis 0):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


- Reversing Along Columns (axis 1): Reversing along columns means flipping the array horizontally.

- Method 2: Using Slicing ([:, ::-1]): We can slice the array along the columns (axis 1) using the following:

In [ ]:
# Reverse along columns (axis 1)
reversed_columns = arr_2d[:, ::-1]

print("Reversed along columns (axis 1):\n", reversed_columns)


Reversed along columns (axis 1):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


- Reversing Along Both Axes (axis 0 and 1) : Reversing along both axes will flip the array both vertically and horizontally.

- Method 3: Using Slicing ([::-1, ::-1]) : This reverses both rows and columns.

In [ ]:
# Reverse along both axes (axis 0 and 1)
reversed_both = arr_2d[::-1, ::-1]

print("Reversed along both axes (axis 0 and 1):\n", reversed_both)


Reversed along both axes (axis 0 and 1):
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


##4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.



#### We can determine the data type of elements in a NumPy array using the dtype attribute.This data type defines the kind of data stored in the array (e.g., integers, floats, complex numbers).

In [ ]:
# Create NumPy arrays with different data types
arr_int = np.array([1, 2, 3, 4])
arr_float = np.array([1.1, 2.2, 3.3, 4.4])
arr_complex = np.array([1+2j, 2+3j, 3+4j])

# Access the data type of each array
print("Data type of arr_int:", arr_int.dtype)
print("Data type of arr_float:", arr_float.dtype)
print("Data type of arr_complex:", arr_complex.dtype)


Data type of arr_int: int64
Data type of arr_float: float64
Data type of arr_complex: complex128


#### Importance of Data Types in Memory Management: The data type of a NumPy array has a significant impact on its memory usage. Different data types require different amounts of memory. For example:

- int8: 1 byte
- int16: 2 bytes
- int32: 4 bytes
- int64: 8 bytes
- float32: 4 bytes
- float64: 8 bytes
- complex128: 16 bytes

####Explanation: Here, arr_int uses 16 bytes (4 elements * 4 bytes per int32), while arr_float uses 32 bytes (4 elements * 8 bytes per float64).
Choosing a smaller data type (e.g., int8, float32) can save memory when the range of values is known to be small and precision requirements are lower.

In [ ]:
arr_int = np.array([1, 2, 3, 4], dtype=np.int32)
arr_float = np.array([1.1, 2.2, 3.3, 4.4], dtype=np.float64)

print("Memory usage of arr_int:", arr_int.nbytes)   # In bytes
print("Memory usage of arr_float:", arr_float.nbytes) # In bytes


Memory usage of arr_int: 16
Memory usage of arr_float: 32


####Impact of Data Types on Performance
The data type also affects the performance of operations on NumPy arrays:

1. Memory Access Speed:
- Smaller data types (e.g., int8, float32) require less memory, leading to better cache utilization, which improves performance for large arrays.
- Larger data types (e.g., float64, complex128) require more memory and can slow down operations, especially with large arrays, due to greater memory bandwidth consumption.
2. Computational Speed:
Operations involving smaller data types may be faster due to lower memory access and smaller data to process.
For example, matrix multiplication with float32 data type can be faster than float64 because the former involves less data transfer between memory and CPU.
- Explanation: Operations on float32 arrays are faster because they involve less memory usage and fewer bytes to process compared to float64 arrays.

In [ ]:
import time

# Create large arrays with different data types
arr1 = np.random.rand(1000000).astype(np.float32)  # 1 million elements
arr2 = np.random.rand(1000000).astype(np.float64)  # 1 million elements

# Measure time for operations on float32
start_time = time.time()
arr1 + arr1  # Adding the array to itself
print("Time taken for float32:", time.time() - start_time)

# Measure time for operations on float64
start_time = time.time()
arr2 + arr2  # Adding the array to itself
print("Time taken for float64:", time.time() - start_time)


Time taken for float32: 0.001528024673461914
Time taken for float64: 0.0020563602447509766


 #### Choosing the Right dtype:
- Use smaller types (int32, float32) for memory efficiency and speed when high precision isn't necessary.
- Use larger types (float64, complex128) when higher precision is required, but they consume more memory and may slow down computations.

In [ ]:
# A large 2D array where memory usage is a concern
arr_large = np.zeros((10000, 10000), dtype=np.float32)  # Using float32 to save memory

# A high-precision calculation
arr_precise = np.zeros((10000, 10000), dtype=np.float64)  # Using float64 for better precision


##5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

An ndarray (short for n-dimensional array) is the core data structure in NumPy that provides efficient, fast, and flexible ways to handle large datasets in n dimensions. It is a homogeneous array, meaning all elements must be of the same data type (e.g., integers, floats).

- Key Features of ndarray in NumPy:

1. Homogeneity: All elements in an ndarray must be of the same type (e.g., all integers or all floats).
This allows NumPy to optimize storage and operations, making it more efficient than Python lists, which can store mixed data types.

2. Multi-dimensional: Unlike Python lists (which are 1D by default), NumPy arrays can be n-dimensional, meaning they can represent data in 1D, 2D (matrices), 3D (tensors), and higher-dimensional arrays.
The shape of the array (a tuple representing the dimensions) is an important feature of ndarray.

3. Efficient Storage and Operations: NumPy arrays are stored contiguously in memory, making it efficient for large datasets. This allows for fast, vectorized operations on the entire array, which is not possible with Python lists.
Element-wise operations (like addition, subtraction, etc.) can be done directly on NumPy arrays without the need for explicit loops.

4. Element-wise Operations: NumPy supports vectorized operations, meaning that you can perform operations (like addition, multiplication) on entire arrays or subarrays without explicitly using loops. This makes the code more concise and improves performance.

5. Broadcasting: Broadcasting is a powerful feature in NumPy that allows you to perform operations on arrays of different shapes. The smaller array is "broadcast" over the larger array so that they have compatible shapes.
This allows operations on arrays of different dimensions without having to reshape or replicate data.

6. Memory Efficiency: ndarrays are more memory efficient than Python lists because they store data in a fixed-size, contiguous block of memory. This means NumPy arrays use less memory and allow for faster access to the elements.

7. Methods and Functions: NumPy provides a rich set of methods for ndarray objects (e.g., reshape(), transpose(), sum(), mean(), etc.) and allows you to perform operations on arrays efficiently. These methods are highly optimized for performance.

8. Array Slicing and Indexing: We can slice and index NumPy arrays similarly to Python lists, but NumPy provides more powerful ways to do this, such as boolean indexing and fancy indexing, enabling efficient selection of subsets of data.




In [ ]:
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

# Element-wise operations
arr2 = arr * 2
print(arr2)

# Sum of elements
print(np.sum(arr))


[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
21


## 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Performance Benefits of NumPy Arrays Over Python Lists for Large-Scale Numerical Operations:
1. Memory Efficiency: NumPy arrays are stored in contiguous memory blocks with a homogeneous data type, resulting in more compact storage and faster data access.
Python lists store elements as pointers, leading to more memory overhead and slower access.

2. Speed: NumPy supports vectorized operations, allowing element-wise operations to be performed in one operation at the C level, significantly faster than Python's loop-based approach.
Python lists require explicit loops for element-wise operations, which is slower due to Python's interpreted nature.

3. Broadcasting: NumPy supports broadcasting, allowing operations between arrays of different shapes without explicit reshaping, leading to cleaner code and better performance.
Python lists lack broadcasting, requiring manual reshaping and more complex code.
4. Parallelism and Optimized Libraries: NumPy leverages multi-threading and optimized libraries like BLAS and LAPACK, boosting performance for large datasets and complex computations.
Python lists don’t have built-in parallelism or optimized numerical libraries.
5. Scalability: NumPy efficiently handles large datasets, maintaining performance even as the data size grows.
Python lists become slower and less memory-efficient for large-scale operations.

In [ ]:
import numpy as np

arr1 = np.random.rand(1000000)
arr2 = np.random.rand(1000000)
result = arr1 + arr2  # Vectorized operation


In [ ]:
arr1 = [1] * 1000000
arr2 = [2] * 1000000
result = [arr1[i] + arr2[i] for i in range(len(arr1))]  # Manual iteration


In [ ]:
import numpy as np
import time

# Create large arrays
size = 10**7
arr1_np = np.random.rand(size)
arr2_np = np.random.rand(size)

arr1_lst = list(np.random.rand(size))
arr2_lst = list(np.random.rand(size))

# NumPy operation
start = time.time()
result_np = arr1_np + arr2_np  # Vectorized operation
end = time.time()
print(f"NumPy operation took {end - start:.6f} seconds.")

# Python list operation
start = time.time()
result_lst = [arr1_lst[i] + arr2_lst[i] for i in range(size)]  # Manual iteration
end = time.time()
print(f"Python list operation took {end - start:.6f} seconds.")


NumPy operation took 0.064672 seconds.
Python list operation took 4.065828 seconds.


## 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In NumPy, vstack() and hstack() are used to stack arrays along different axes, but they differ in how they stack the arrays.

vstack(): Stacks arrays vertically (along the first axis), meaning it joins arrays along rows.
hstack(): Stacks arrays horizontally (along the second axis), meaning it joins arrays along columns.
1. vstack() (Vertical Stack)
Function: Stacks arrays along the rows (vertically). The number of columns must be the same for all arrays being stacked.
2. hstack() (Horizontal Stack)
Function: Stacks arrays along the columns (horizontally). The number of rows must be the same for all arrays being stacked.

In [ ]:
import numpy as np

# Define two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Stack arrays vertically
stacked_v = np.vstack((array1, array2))

print(stacked_v)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np

# Define two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Stack arrays horizontally
stacked_h = np.hstack((array1, array2))

print(stacked_h)


[[1 2 5 6]
 [3 4 7 8]]


## 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In NumPy, the methods fliplr() and flipud() are used to flip arrays along different axes. These methods are designed to flip the contents of arrays either left-to-right or up-to-down, respectively, and are primarily used with 2D arrays, though they can work with other dimensions as well.

1. fliplr() (Flip Left-Right)
Function: Flips an array horizontally (i.e., along the left-right axis, the second axis of the array).
Axis: Flips the contents of the array along axis 1 (columns).
Effect: Reverses the order of elements along each row.




In [ ]:
import numpy as np

# Define a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Flip the array left-to-right
flipped_lr = np.fliplr(array)

print(flipped_lr)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


2. flipud() (Flip Up-Down)
Function: Flips an array vertically (i.e., along the up-down axis, the first axis of the array).
Axis: Flips the contents of the array along axis 0 (rows).
Effect: Reverses the order of rows in the array.

In [ ]:
# Define a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Flip the array up-to-down
flipped_ud = np.flipud(array)

print(flipped_ud)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


- Effects on Arrays of Different Dimensions:

1D Array: Neither fliplr() nor flipud() is applicable to a 1D array in a meaningful way, as there are no columns or rows to flip.

fliplr() will still reverse the entire array as it would for a 1D case.
flipud() does not make sense for 1D arrays.

####Effects on Arrays of Different Dimensions:
- 1D Array: Neither fliplr() nor flipud() is applicable to a 1D array in a meaningful way, as there are no columns or rows to flip.

fliplr() will still reverse the entire array as it would for a 1D case. flipud() does not make sense for 1D arrays.
- 2D Array: Both methods are useful and behave as described.

- 3D Array: fliplr() will flip the array along the second axis (columns), affecting the elements within each "slice" of the 3D array.
flipud() will flip the array along the first axis (rows), affecting the order of 2D slices along the first axis.

In [ ]:
import numpy as np

# Define a 3D array (2 layers, 3 rows, 3 columns)
array = np.array([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]],
                  [[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]]])

# Flip horizontally (left-right)
flipped_lr_3d = np.fliplr(array)

# Flip vertically (up-down)
flipped_ud_3d = np.flipud(array)

print("Original 3D array:\n", array)
print("\nFlipped Left-Right 3D array:\n", flipped_lr_3d)
print("\nFlipped Up-Down 3D array:\n", flipped_ud_3d)


Original 3D array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]

Flipped Left-Right 3D array:
 [[[ 7  8  9]
  [ 4  5  6]
  [ 1  2  3]]

 [[16 17 18]
  [13 14 15]
  [10 11 12]]]

Flipped Up-Down 3D array:
 [[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]


## 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?


The array_split() method in NumPy is a flexible way to split an array into multiple sub-arrays. It differs from the split() method in that it can handle cases where the array cannot be evenly divided into the specified number of parts. If the division is not exact, array_split() attempts to split the array as evenly as possible.

- Functionality of array_split():
1. Even Splits: If the array can be evenly divided, it will split into equal parts.
2. Uneven Splits: If the array cannot be evenly divided (e.g., splitting 7 elements into 3 parts), array_split() will distribute the extra elements as evenly as possible:
- It ensures no sub-array has more than one element more than another.
- The extra elements are added to the first few sub-arrays.
The Uneven Splits Are Handled:
The array has 7 elements, and splitting it into 3 parts results in:
The first sub-array gets 3 elements ([1, 2, 3]).
The second and third sub-arrays get 2 elements each ([4, 5] and [6, 7]).
Thus, array_split() ensures the split is as even as possible, even when the total number of elements cannot be evenly divided by the number of sections.

In [27]:
import numpy as np

# Define an array of 7 elements
array = np.array([1, 2, 3, 4, 5, 6, 7])

# Split into 3 parts
split_array = np.array_split(array, 3)

print("Array split into 3 parts:")
for part in split_array:
    print(part)


Array split into 3 parts:
[1 2 3]
[4 5]
[6 7]


## 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?


In NumPy, vectorization and broadcasting are two powerful concepts that enable efficient operations on arrays. They allow you to perform array-wide operations without the need for explicit loops, which enhances both the performance and readability of your code.

1. Vectorization in NumPy
Vectorization refers to the ability to perform operations on entire arrays (or large parts of arrays) at once, instead of iterating over individual elements using loops. This is possible because NumPy operations are implemented in C and optimized for performance. By performing operations on entire arrays at once, NumPy leverages low-level optimizations that are much faster than the corresponding Python-level loops.

In [28]:
import numpy as np

# Two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vectorized addition
result = arr1 + arr2
print(result)


[5 7 9]


2. Broadcasting in NumPy
Broadcasting is a technique that allows NumPy to perform element-wise operations on arrays of different shapes. Instead of requiring that arrays have the same shape, NumPy will "broadcast" the smaller array to match the dimensions of the larger one in certain situations. Broadcasting automatically expands the dimensions of the smaller array to be compatible with the larger array, allowing element-wise operations to proceed without explicitly reshaping the arrays.

####Rules of Broadcasting:

- If the arrays have a different number of dimensions, the smaller array is padded with ones on the left side until both arrays have the same number of dimensions.
- The shape of the arrays is compatible if, for each dimension, the size of the smaller array is either 1 or matches the size of the corresponding dimension of the larger array.
- If the size of a dimension is 1 in one array, NumPy can broadcast it to match the corresponding dimension in the other array.
- If the sizes do not match and neither is 1, broadcasting cannot be performed, and a ValueError is raised.

In [29]:
import numpy as np

# A 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Adding a scalar (1D array with a single element) to each element of arr
result = arr + 10
print(result)


[[11 12 13]
 [14 15 16]]


In [30]:
# A 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# A 1D array
arr2 = np.array([10, 20, 30])

# Broadcasting arr2 to match the shape of arr
result = arr + arr2
print(result)


[[11 22 33]
 [14 25 36]]


The Vectorization and Broadcasting Contribute to Efficient Array Operations
Vectorization:

Avoids loops: NumPy internally uses optimized, compiled code to perform operations, which is significantly faster than using Python loops.
Parallelism: Vectorized operations are often executed in parallel at the CPU level, taking advantage of multiple cores and SIMD (Single Instruction, Multiple Data) instructions.
Concise code: You can write simpler, more readable code without worrying about iteration.
Broadcasting:

Avoids reshaping: You don't need to manually adjust array shapes with reshape() or tile(). Broadcasting automatically expands smaller arrays to match the shape of larger arrays.
Memory efficiency: Broadcasting does not create unnecessary copies of data. Instead, it creates a view of the original arrays, so it's memory-efficient.
Simplified code: You can perform operations on arrays of different shapes without having to explicitly match their sizes, leading to cleaner and more intuitive code.


# PRACTICAL QUESTIONS

 ## 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

 To create a 3x3 NumPy array with random integers between 1 and 100 and then interchange its rows and columns (i.e., transpose the array), you can use the following code:

 - Explanation:np.random.randint(1, 101, size=(3, 3)): Generates a 3x3 array of random integers in the range from 1 to 100 (inclusive).
- .T: This is a shorthand to transpose the array, which interchanges rows and columns.

In [ ]:
# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Transpose the array (interchange rows and columns)
arr_transposed = arr.T
print("\nTransposed Array:")
print(arr_transposed)
#In the transposed array, the rows of the original array have become the columns, and the columns have become the rows.


Original Array:
[[24 83 46]
 [ 3 96  8]
 [89 87 15]]

Transposed Array:
[[24  3 89]
 [83 96 87]
 [46  8 15]]


##2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
# Create a 1D array with 10 elements
arr_1d = np.arange(1, 11)  # This will create an array [1, 2, ..., 10]
print("Original 1D Array:")
print(arr_1d)

# Reshape the 1D array into a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(arr_2x5)

# Reshape the 1D array into a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(arr_5x2)


Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped into 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped into 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


##3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:


# Create a 4x4 array with random float values between 0 and 1
arr = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(arr)

# Add a border of zeros around the array, making it 6x6
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:")
print(arr_with_border)


Original 4x4 Array:
[[0.0752184  0.27459062 0.98750074 0.49555483]
 [0.87124235 0.32010728 0.61024677 0.80920845]
 [0.60550896 0.52483144 0.90922689 0.15807005]
 [0.48950488 0.79645652 0.80251076 0.17755959]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.0752184  0.27459062 0.98750074 0.49555483 0.        ]
 [0.         0.87124235 0.32010728 0.61024677 0.80920845 0.        ]
 [0.         0.60550896 0.52483144 0.90922689 0.15807005 0.        ]
 [0.         0.48950488 0.79645652 0.80251076 0.17755959 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


##4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.




In [ ]:
# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)
print("Array of integers from 10 to 60 with a step of 5:")
print(arr)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


##5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.

In [ ]:
# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations to each element
uppercase_arr = np.char.upper(arr)  # Convert to uppercase
lowercase_arr = np.char.lower(arr)  # Convert to lowercase
titlecase_arr = np.char.title(arr)  # Convert to title case (capitalize first letter)
capitalize_arr = np.char.capitalize(arr)  # Capitalize first letter of each string

# Print the original and transformed arrays
print("Original Array:")
print(arr)

print("\nUppercase Transformation:")
print(uppercase_arr)

print("\nLowercase Transformation:")
print(lowercase_arr)

print("\nTitlecase Transformation:")
print(titlecase_arr)

print("\nCapitalize Transformation:")
print(capitalize_arr)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation:
['python' 'numpy' 'pandas']

Titlecase Transformation:
['Python' 'Numpy' 'Pandas']

Capitalize Transformation:
['Python' 'Numpy' 'Pandas']


## 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
# Create a NumPy array of words
arr = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
arr_with_spaces = np.char.join(' ', arr)

# Print the original and transformed arrays
print("Original Array:")
print(arr)

print("\nArray with spaces between characters:")
print(arr_with_spaces)


Original Array:
['python' 'numpy' 'pandas']

Array with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


## 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
import numpy as np

# Create a NumPy array of words
arr = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
arr_with_spaces = np.char.join(' ', arr)

# Print the original and transformed arrays
print("Original Array:")
print(arr)

print("\nArray with spaces between characters:")
print(arr_with_spaces)


## 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [ ]:
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5, 4], [3, 2, 1]])

# Element-wise addition
addition_result = arr1 + arr2

# Element-wise subtraction
subtraction_result = arr1 - arr2

# Element-wise multiplication
multiplication_result = arr1 * arr2

# Element-wise division
# Avoid division by zero
division_result = arr1 / arr2

# Print the results
print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nElement-wise Addition (arr1 + arr2):")
print(addition_result)

print("\nElement-wise Subtraction (arr1 - arr2):")
print(subtraction_result)

print("\nElement-wise Multiplication (arr1 * arr2):")
print(multiplication_result)

print("\nElement-wise Division (arr1 / arr2):")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[6 5 4]
 [3 2 1]]

Element-wise Addition (arr1 + arr2):
[[7 7 7]
 [7 7 7]]

Element-wise Subtraction (arr1 - arr2):
[[-5 -3 -1]
 [ 1  3  5]]

Element-wise Multiplication (arr1 * arr2):
[[ 6 10 12]
 [12 10  6]]

Element-wise Division (arr1 / arr2):
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


## 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = identity_matrix.diagonal()
print("\nDiagonal Elements of the Identity Matrix:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements of the Identity Matrix:
[1. 1. 1. 1. 1.]


## 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in  this array.

In [ ]:

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, size=100)
print("Array of Random Integers:")
print(arr)

# Find all prime numbers in the array using the is_prime function
prime_numbers = [num for num in arr if is_prime(num)]

print("\nPrime Numbers in the Array:")
print(prime_numbers)


Array of Random Integers:
[632 210 274 660 141 452 659 676  96 541 830 270 987 241 441  56 340  44
 393 625 221 867 393 620 644 469 105 638 391 876 455 824 689  72 855 416
 947 176 243 210 292 164 829 948 295 748 433 181 161 455  71  56  44 426
 976 433  43 339 542 655 207 109 207 212 554 411 308 717 690 206 485 332
 285 689 207  47 849 434 447 707  13 688 487 666 214 941 874 737 230 186
 389 197 537 393  72 238 577 843 850 964]

Prime Numbers in the Array:
[659, 541, 241, 947, 829, 433, 181, 71, 433, 43, 109, 47, 13, 487, 941, 389, 197, 577]


## 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [ ]:
import numpy as np

# Step 1: Create a NumPy array of daily temperatures for a month (30 days)
# Using random integers between 15 and 35 degrees Celsius for simplicity
daily_temperatures = np.random.randint(15, 36, size=28)
print("Daily Temperatures for the Month (30 Days):")
print(daily_temperatures)

# Step 2: Reshape the array to represent 4 full weeks of 7 days and 2 extra days
# In reality, there are 4 full weeks (28 days) and the last two days would be extra
weekly_temperatures = daily_temperatures.reshape(4, 7)
print("\nTemperatures Reshaped into Weekly Data (4 Weeks of 7 Days):")
print(weekly_temperatures)

# Step 3: Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)
print("\nWeekly Average Temperatures:")
print(weekly_averages)


Daily Temperatures for the Month (30 Days):
[24 34 25 31 21 30 20 33 21 17 23 20 17 16 30 33 22 25 23 28 22 22 27 27
 20 35 16 31]

Temperatures Reshaped into Weekly Data (4 Weeks of 7 Days):
[[24 34 25 31 21 30 20]
 [33 21 17 23 20 17 16]
 [30 33 22 25 23 28 22]
 [22 27 27 20 35 16 31]]

Weekly Average Temperatures:
[26.42857143 21.         26.14285714 25.42857143]
